In [ ]:
from google.colab import files
uploaded = files.upload()

Saving archive (1).zip to archive (1).zip

In [ ]:
import zipfile
import os

In [ ]:
with zipfile.ZipFile("archive (1).zip", "r") as zip_ref:
    zip_ref.extractall("data")

In [ ]:
print(os.listdir("data"))

['players.csv']

In [ ]:
import pandas as pd
print("Pandas Library Imported Successfully")

Pandas Library Imported Successfully

In [ ]:
import pandas as pd
df = pd.read_csv("data/players.csv")
print(df)

                  player        team team_country position     age  \
0           Achref Abada     Algeria      Algeria       DF  27-020
1          Adil Boulbina     Algeria      Algeria       FW  23-064
2           Amine Gouiri     Algeria      Algeria       FW  26-139
3       Anis Hadj Moussa     Algeria      Algeria       MF  24-144
4            Aïssa Mandi     Algeria      Algeria       DF  34-256
...                  ...         ...          ...      ...     ...
1242   Rustam Ashurmatov  Uzbekistan   Uzbekistan       DF  29-363
1243      Sherzod Esanov  Uzbekistan   Uzbekistan       MF  23-154
1244  Sherzod Nasrullaev  Uzbekistan   Uzbekistan    DF,MF  27-347
1245     Umar Eshmurodov  Uzbekistan   Uzbekistan       DF  33-217
1246       Utkir Yusupov  Uzbekistan   Uzbekistan       GK  35-182

      birth_year       club  games  games_starts  minutes  ...  gk_wins  \
0           1999        NaN      0             0      NaN  ...      NaN
1           2003        NaN      2             0     19.0  ...      NaN
2           2000  Marseille      4             3    251.0  ...      NaN
3           2002  Feyenoord      3             1     98.0  ...      NaN
4           1991      Lille      4             4    360.0  ...      NaN
...          ...        ...    ...           ...      ...  ...      ...
1242        1996  Esteghlal      3             3    256.0  ...      NaN
1243        2003        NaN      1             0      1.0  ...      NaN
1244        1998        NaN      3             3    180.0  ...      NaN
1245        1992        NaN      0             0      NaN  ...      NaN
1246        1991        NaN      1             1     90.0  ...      0.0

      gk_ties  gk_losses  gk_clean_sheets  gk_clean_sheets_pct  gk_pens_att  \
0         NaN        NaN              NaN                  NaN          NaN
1         NaN        NaN              NaN                  NaN          NaN
2         NaN        NaN              NaN                  NaN          NaN
3         NaN        NaN              NaN                  NaN          NaN
4         NaN        NaN              NaN                  NaN          NaN
...       ...        ...              ...                  ...          ...
1242      NaN        NaN              NaN                  NaN          NaN
1243      NaN        NaN              NaN                  NaN          NaN
1244      NaN        NaN              NaN                  NaN          NaN
1245      NaN        NaN              NaN                  NaN          NaN
1246      0.0        1.0              0.0                  0.0          0.0

      gk_pens_allowed  gk_pens_saved  gk_pens_missed  gk_pens_save_pct
0                 NaN            NaN             NaN               NaN
1                 NaN            NaN             NaN               NaN
2                 NaN            NaN             NaN               NaN
3                 NaN            NaN             NaN               NaN
4                 NaN            NaN             NaN               NaN
...               ...            ...             ...               ...
1242              NaN            NaN             NaN               NaN
1243              NaN            NaN             NaN               NaN
1244              NaN            NaN             NaN               NaN
1245              NaN            NaN             NaN               NaN
1246              0.0            0.0             0.0               NaN

[1247 rows x 72 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("data/players.csv")
print(df.head())

             player     team team_country position     age  birth_year  \
0      Achref Abada  Algeria      Algeria       DF  27-020        1999
1     Adil Boulbina  Algeria      Algeria       FW  23-064        2003
2      Amine Gouiri  Algeria      Algeria       FW  26-139        2000
3  Anis Hadj Moussa  Algeria      Algeria       MF  24-144        2002
4       Aïssa Mandi  Algeria      Algeria       DF  34-256        1991

        club  games  games_starts  minutes  ...  gk_wins  gk_ties  gk_losses  \
0        NaN      0             0      NaN  ...      NaN      NaN        NaN
1        NaN      2             0     19.0  ...      NaN      NaN        NaN
2  Marseille      4             3    251.0  ...      NaN      NaN        NaN
3  Feyenoord      3             1     98.0  ...      NaN      NaN        NaN
4      Lille      4             4    360.0  ...      NaN      NaN        NaN

   gk_clean_sheets  gk_clean_sheets_pct  gk_pens_att  gk_pens_allowed  \
0              NaN                  NaN          NaN              NaN
1              NaN                  NaN          NaN              NaN
2              NaN                  NaN          NaN              NaN
3              NaN                  NaN          NaN              NaN
4              NaN                  NaN          NaN              NaN

   gk_pens_saved  gk_pens_missed  gk_pens_save_pct
0            NaN             NaN               NaN
1            NaN             NaN               NaN
2            NaN             NaN               NaN
3            NaN             NaN               NaN
4            NaN             NaN               NaN

[5 rows x 72 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("data/players.csv")
print(df.tail())

                  player        team team_country position     age  \
1242   Rustam Ashurmatov  Uzbekistan   Uzbekistan       DF  29-363
1243      Sherzod Esanov  Uzbekistan   Uzbekistan       MF  23-154
1244  Sherzod Nasrullaev  Uzbekistan   Uzbekistan    DF,MF  27-347
1245     Umar Eshmurodov  Uzbekistan   Uzbekistan       DF  33-217
1246       Utkir Yusupov  Uzbekistan   Uzbekistan       GK  35-182

      birth_year       club  games  games_starts  minutes  ...  gk_wins  \
1242        1996  Esteghlal      3             3    256.0  ...      NaN
1243        2003        NaN      1             0      1.0  ...      NaN
1244        1998        NaN      3             3    180.0  ...      NaN
1245        1992        NaN      0             0      NaN  ...      NaN
1246        1991        NaN      1             1     90.0  ...      0.0

      gk_ties  gk_losses  gk_clean_sheets  gk_clean_sheets_pct  gk_pens_att  \
1242      NaN        NaN              NaN                  NaN          NaN
1243      NaN        NaN              NaN                  NaN          NaN
1244      NaN        NaN              NaN                  NaN          NaN
1245      NaN        NaN              NaN                  NaN          NaN
1246      0.0        1.0              0.0                  0.0          0.0

      gk_pens_allowed  gk_pens_saved  gk_pens_missed  gk_pens_save_pct
1242              NaN            NaN             NaN               NaN
1243              NaN            NaN             NaN               NaN
1244              NaN            NaN             NaN               NaN
1245              NaN            NaN             NaN               NaN
1246              0.0            0.0             0.0               NaN

[5 rows x 72 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("data/players.csv")
print(df.shape)

(1247, 72)

In [ ]:
import pandas as pd
df = pd.read_csv("data/players.csv")
print(df.columns)

Index(['player', 'team', 'team_country', 'position', 'age', 'birth_year',
       'club', 'games', 'games_starts', 'minutes', 'minutes_90s', 'goals',
       'assists', 'goals_assists', 'goals_pens', 'pens_made', 'pens_att',
       'cards_yellow', 'cards_red', 'goals_per90', 'assists_per90',
       'goals_assists_per90', 'goals_pens_per90', 'goals_assists_pens_per90',
       'shots', 'shots_on_target', 'shots_on_target_pct', 'shots_per90',
       'shots_on_target_per90', 'goals_per_shot', 'goals_per_shot_on_target',
       'minutes_per_game', 'minutes_pct', 'minutes_per_start',
       'games_complete', 'games_subs', 'minutes_per_sub', 'unused_subs',
       'points_per_game', 'on_goals_for', 'on_goals_against', 'plus_minus',
       'plus_minus_per90', 'plus_minus_wowy', 'cards_yellow_red', 'fouls',
       'fouled', 'offsides', 'crosses', 'interceptions', 'tackles_won',
       'pens_won', 'pens_conceded', 'own_goals', 'gk_games', 'gk_games_starts',
       'gk_minutes', 'gk_goals_against', 'gk_goals_against_per90',
       'gk_shots_on_target_against', 'gk_saves', 'gk_save_pct', 'gk_wins',
       'gk_ties', 'gk_losses', 'gk_clean_sheets', 'gk_clean_sheets_pct',
       'gk_pens_att', 'gk_pens_allowed', 'gk_pens_saved', 'gk_pens_missed',
       'gk_pens_save_pct'],
      dtype='object')

In [ ]:
import pandas as pd
df = pd.read_csv("data/players.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1247 entries, 0 to 1246
Data columns (total 72 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   player                      1247 non-null   object
 1   team                        1247 non-null   object
 2   team_country                1247 non-null   object
 3   position                    1247 non-null   object
 4   age                         1247 non-null   object
 5   birth_year                  1247 non-null   int64
 6   club                        891 non-null    object
 7   games                       1247 non-null   int64
 8   games_starts                1247 non-null   int64
 9   minutes                     1023 non-null   float64
 10  minutes_90s                 1023 non-null   float64
 11  goals                       1023 non-null   float64
 12  assists                     1023 non-null   float64
 13  goals_assists               1023 non-null   float64
 14  goals_pens                  1023 non-null   float64
 15  pens_made                   1023 non-null   float64
 16  pens_att                    1023 non-null   float64
 17  cards_yellow                1023 non-null   float64
 18  cards_red                   1023 non-null   float64
 19  goals_per90                 1023 non-null   float64
 20  assists_per90               1023 non-null   float64
 21  goals_assists_per90         1023 non-null   float64
 22  goals_pens_per90            1023 non-null   float64
 23  goals_assists_pens_per90    1023 non-null   float64
 24  shots                       1023 non-null   float64
 25  shots_on_target             1023 non-null   float64
 26  shots_on_target_pct         662 non-null    float64
 27  shots_per90                 1023 non-null   float64
 28  shots_on_target_per90       1023 non-null   float64
 29  goals_per_shot              662 non-null    float64
 30  goals_per_shot_on_target    378 non-null    float64
 31  minutes_per_game            1023 non-null   float64
 32  minutes_pct                 1023 non-null   float64
 33  minutes_per_start           768 non-null    float64
 34  games_complete              1247 non-null   int64
 35  games_subs                  1247 non-null   int64
 36  minutes_per_sub             542 non-null    float64
 37  unused_subs                 1247 non-null   int64
 38  points_per_game             1023 non-null   float64
 39  on_goals_for                1023 non-null   float64
 40  on_goals_against            1023 non-null   float64
 41  plus_minus                  1023 non-null   float64
 42  plus_minus_per90            1023 non-null   float64
 43  plus_minus_wowy             900 non-null    float64
 44  cards_yellow_red            1023 non-null   float64
 45  fouls                       1023 non-null   float64
 46  fouled                      1023 non-null   float64
 47  offsides                    1023 non-null   float64
 48  crosses                     1023 non-null   float64
 49  interceptions               1023 non-null   float64
 50  tackles_won                 1023 non-null   float64
 51  pens_won                    0 non-null      float64
 52  pens_conceded               0 non-null      float64
 53  own_goals                   1023 non-null   float64
 54  gk_games                    60 non-null     float64
 55  gk_games_starts             60 non-null     float64
 56  gk_minutes                  60 non-null     float64
 57  gk_goals_against            60 non-null     float64
 58  gk_goals_against_per90      60 non-null     float64
 59  gk_shots_on_target_against  60 non-null     float64
 60  gk_saves                    60 non-null     float64
 61  gk_save_pct                 57 non-null     float64
 62  gk_wins                     60 non-null     float64
 63  gk_ties                     60 non-null     float64
 64  gk_losses                   60 non-null     float64
 65  gk_clean_sheets             60 non-null     float64
 66  gk_clean_sheets_pct         57 non-null     float64
 67  gk_pens_att                 60 non-null     float64
 68  gk_pens_allowed             60 non-null     float64
 69  gk_pens_saved               60 non-null     float64
 70  gk_pens_missed              60 non-null     float64
 71  gk_pens_save_pct            11 non-null     float64
dtypes: float64(60), int64(6), object(6)
memory usage: 701.6+ KB

In [ ]:
import pandas as pd
df = pd.read_csv("data/players.csv")
print(df.describe())

        birth_year        games  games_starts      minutes  minutes_90s  \
count  1247.000000  1247.000000   1247.000000  1023.000000  1023.000000
mean   1998.036889     2.277466      1.587811   177.093842     1.966960
std       4.257022     1.487777      1.543415   120.837695     1.341576
min    1982.000000     0.000000      0.000000     1.000000     0.000000
25%    1995.000000     1.000000      0.000000    67.500000     0.750000
50%    1998.000000     3.000000      1.000000   173.000000     1.900000
75%    2001.000000     4.000000      3.000000   270.000000     3.000000
max    2008.000000     5.000000      5.000000   480.000000     5.300000

             goals      assists  goals_assists   goals_pens    pens_made  ...  \
count  1023.000000  1023.000000    1023.000000  1023.000000  1023.000000  ...
mean      0.242424     0.185728       0.428152     0.231672     0.010753  ...
std       0.693751     0.510853       0.942822     0.662154     0.103187  ...
min       0.000000     0.000000       0.000000     0.000000     0.000000  ...
25%       0.000000     0.000000       0.000000     0.000000     0.000000  ...
50%       0.000000     0.000000       0.000000     0.000000     0.000000  ...
75%       0.000000     0.000000       1.000000     0.000000     0.000000  ...
max       7.000000     5.000000       9.000000     7.000000     1.000000  ...

         gk_wins    gk_ties  gk_losses  gk_clean_sheets  gk_clean_sheets_pct  \
count  60.000000  60.000000  60.000000        60.000000            57.000000
mean    1.116667   0.766667   1.116667         0.850000            23.770175
std     1.290009   0.889995   0.940459         1.070799            28.956013
min     0.000000   0.000000   0.000000         0.000000             0.000000
25%     0.000000   0.000000   0.000000         0.000000             0.000000
50%     1.000000   1.000000   1.000000         0.000000             0.000000
75%     2.000000   1.000000   2.000000         2.000000            50.000000
max     5.000000   3.000000   3.000000         4.000000           100.000000

       gk_pens_att  gk_pens_allowed  gk_pens_saved  gk_pens_missed  \
count    60.000000        60.000000      60.000000       60.000000
mean      0.233333         0.183333       0.033333        0.016667
std       0.499717         0.469102       0.181020        0.129099
min       0.000000         0.000000       0.000000        0.000000
25%       0.000000         0.000000       0.000000        0.000000
50%       0.000000         0.000000       0.000000        0.000000
75%       0.000000         0.000000       0.000000        0.000000
max       2.000000         2.000000       1.000000        1.000000

       gk_pens_save_pct
count         11.000000
mean          18.181818
std           40.451992
min            0.000000
25%            0.000000
50%            0.000000
75%            0.000000
max          100.000000

[8 rows x 66 columns]

In [ ]:
# 9. Display the data type of each column
df.dtypes

player               object
team                 object
team_country         object
position             object
age                  object
                     ...
gk_pens_att         float64
gk_pens_allowed     float64
gk_pens_saved       float64
gk_pens_missed      float64
gk_pens_save_pct    float64
Length: 72, dtype: object

In [ ]:
# 10. Count missing values in each column
df.isnull().sum()

player                 0
team                   0
team_country           0
position               0
age                    0
                    ...
gk_pens_att         1187
gk_pens_allowed     1187
gk_pens_saved       1187
gk_pens_missed      1187
gk_pens_save_pct    1236
Length: 72, dtype: int64

In [ ]:
# 11. Count unique values in each column
df.nunique()

player              1246
team                  48
team_country          48
position               9
age                 1114
                    ...
gk_pens_att            3
gk_pens_allowed        3
gk_pens_saved          2
gk_pens_missed         2
gk_pens_save_pct       2
Length: 72, dtype: int64

In [ ]:
# 12. Display 5 random rows from the dataset
df.sample(5)

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,...,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
1039,Aymeric Laporte,Spain,Spain,DF,32-039,1994,Athletic Club,4,4,359.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Mohamed Amoura,Algeria,Algeria,"FW,MF",26-057,2000,Wolfsburg,1,0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026,Oswin Appollis,South Africa,South Africa,"MF,FW",24-314,2001,Orlando Pirates,4,3,255.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,Kojo Peprah Oppong,Ghana,Ghana,DF,22-031,2004,Nice,2,0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1080,Jacob Widell Zetterström,Sweden,Sweden,GK,27-359,1998,Derby County,2,2,180.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [ ]:
df['team_country'].value_counts()

team_country
Algeria                   26
Argentina                 26
Australia                 26
Austria                   26
Bosnia and Herzegovina    26
Brazil                    26
Cape Verde                26
Canada                    26
Curaçao                   26
Colombia                  26
Congo DR                  26
Croatia                   26
Côte d'Ivoire             26
Czech Republic            26
Ecuador                   26
Egypt                     26
Panama                    26
England                   26
France                    26
Germany                   26
Ghana                     26
Haiti                     26
Iran                      26
Iraq                      26
Japan                     26
Jordan                    26
Korea Republic            26
Mexico                    26
Morocco                   26
Netherlands               26
New Zealand               26
Norway                    26
Spain                     26
Paraguay                  26
Portugal                  26
Qatar                     26
Saudi Arabia              26
Scotland                  26
Senegal                   26
South Africa              26
Turkey                    26
Sweden                    26
Switzerland               26
Tunisia                   26
Uruguay                   26
United States             26
Uzbekistan                26
Belgium                   25
Name: count, dtype: int64

In [ ]:
!git config --global user.name "bodkhesakshi03-dotcom"

In [ ]:
!git config --global user.email "bodkhesakshi03"

In [ ]:
!git clone https://bodkhesakshi03-dotcom:ghp_ABC123xyz@github.com/bodkhesakshi03-dotcom/AIML_Special_Task.git

Cloning into 'AIML_Special_Task'...
warning: You appear to have cloned an empty repository.

In [ ]:
!ls /content

 AIML_Special_Task  'archive (1).zip'   data   sample_data

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving special_task.ipynb to special_task.ipynb

In [ ]:
!ls /content

 AIML_Special_Task  'archive (1).zip'   data   sample_data   special_task.ipynb

In [ ]:

%cd /content/AIML_Special_Task/

/content/AIML_Special_Task

In [ ]:
!git status

In [ ]:
!git status

On branch main
Your branch and 'origin/main' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

In [ ]:
!git commit -m "Merge remote changes"

[main 135454d] Merge remote changes

In [ ]:
!git push origin main

Enumerating objects: 2, done.
Counting objects: 100% (2/2), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 303 bytes | 303.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/bodkhesakshi03-dotcom/AIML_Special_Task.git
   e373b37..135454d  main -> main

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [ ]:
!git log --oneline -3

135454d (HEAD -> main, origin/main) Merge remote changes
aa27c6a Updated notebook after describe() and other commands
e373b37 Added special_task notebook

In [ ]:
!ls -l /content/AIML_Special_Task

total 44
drwxr-xr-x 3 root root  4096 Jul  6 09:21 AIML_Special_Task
-rw-r--r-- 1 root root 37689 Jul  6 08:40 special_task.ipynb